spring.application.name=gateway-service
server.port=5050

spring.cloud.gateway.routes[0].id=backend-route
spring.cloud.gateway.routes[0].uri=lb://backend-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/**

spring.cloud.discovery.client.simple.instances.backend-service[0].uri=http://backend1:9090
spring.cloud.discovery.client.simple.instances.backend-service[1].uri=http://backend2:9090
spring.cloud.discovery.client.simple.instances.backend-service[2].uri=http://backend3:9090

spring.data.redis.host=redis
spring.data.redis.port=6379